using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NFT.Storage.Net.ClientResponse
{
    /// <summary>
    /// contains information about one or more files
    /// </summary>
    public class ResponseValue
    {
        /// <summary>
        /// the unique identifier of the file
        /// </summary>
        public string cid { get; set; }
        /// <summary>
        /// the time when the file was created
        /// </summary>
        public string created { get; set; }
        /// <summary>
        /// the suspected file type
        /// </summary>
        public string type { get; set; }
        public string scope { get; set; }
        public ResponseFile[] files { get; set; }
        /// <summary>
        /// the size of the file, measured in ???
        /// </summary>
        public int size { get; set; }
        /// <summary>
        /// the name generated by nft.storage (seems to be text + datetime)
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// the pin status of the file
        /// </summary>
		public ResponsePin pin { get; set; }
    }
}
